version: '3'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  chatbot:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - ollama

volumes:
  ollama: