version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  visa-chatbot:
    build: .
    container_name: visa-chatbot
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama:
